# # bs16 --num_steps 10000
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 0.5 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 1.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 2.0 &
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 3.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 4.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 5.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 6.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 7.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 10.0 &&
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 10000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 15.0 &


# # bs16 --num_steps 30000
CUDA_VISIBLE_DEVICES=0,1,2,3 /opt/conda/envs/transfg/bin/python -m torch.distributed.launch --nproc_per_node=4 train.py --output_dir exp01/run01 --dataset CUB_200_2011 --train_batch_size 16 --workers 4 --arch_type Pure --model_type ViT-B_16 --pretrained_dir /root/share/TransFG/logs/pretrained_ViT/imagenet21k_ViT-B_16.npz --split overlap --num_steps 30000 --eval_every 200 --fp16 --name sample_run --round 1 --lambda_0 4.0 &&
